### ISSUE TITLE
Randomly Crashing in Win10 x64

### ISSUE THREAD

**Issue by mynzdro** [Pulover/PuloversMacroCreator#51] opened 2017-06-15 06:49 UTC
Using latest version 5.0.5, and its its randomly crashing. Any solution?
[
![image](https://user-images.githubusercontent.com/29426083/27168768-b3864ca6-51d9-11e7-88e3-56220cabf889.png)
](url)

https://autohotkey.com/boards/viewtopic.php?f=63&t=32902

**Comment by Testertime** [comment] 2017-07-17 15:05
Hi, I can confirm this on Windows 10 32 bit (1511) as well, and I also wish it would tell what exactly is the cause of the crash. Because it always happens utterly random, and sometimes even directly after I started it up, or loaded a script. Exporting the script to Autohotkey is unfortunately no solution either, because it somehow doesn't execute things like intended. Is there no log feature to provide crash logs? Hopefully this will be addressed somewhere in the near future. This great program really has no alternative in my opinion.

**Comment by dbline** [comment] 2018-01-22 03:33
I have the same issue.  Apparently, this project is abandoned now, no responses and no updates for over a year.  Too bad, this was a great program.

**Comment by asas-dev** [comment] 2018-05-15 07:48
Any news on this issue or about the future of this project?

**Comment by Pulover** [comment] 2020-09-14 14:30
Fixed in v5.1.2. [Read more](https://www.macrocreator.com/2020/09/14/version-update-5-1-2/).

**Closed by Pulover** 2020-09-14 14:30 UTC
