### ISSUE TITLE
Some Issues

### ISSUE THREAD

**Issue by chosen1ft** [Pulover/PuloversMacroCreator#114] opened 2020-10-01 15:28 UTC
Version 5.2.6 is working great!!! Thanks a lot!!!

The bugs are getting more and more diffacult to catch. 

1:Creat New Project > Add a mouse command to macro1 > Click "Duplicate Macro" button > Delete the "Mouse" command in macro2 > rename "macro2" to "macro222" . Then the "Mouse" command in macro1 will be deleted too.

2:Creat New Project > Add a  "Key Wait"(Ctrl+F5) command . Then preview zone will show Two command.

![2](https://user-images.githubusercontent.com/69076802/94830003-b15b5100-043d-11eb-8a1b-d736e714078e.png)

3:Creat New Project > Set macro1's hot key to "Esc" or "Backspace" or "None". Then the "Save" button still grey.If set to other hotkey ,the save button will be enabled.

![3](https://user-images.githubusercontent.com/69076802/94830017-b5876e80-043d-11eb-9c90-3f77160e3dcf.png)

**Comment by Pulover** [comment] 2020-10-01 16:39
You are helping a lot.

1.  Confirmed. Will fix it.

2. This is by design.

3. Will see if I can fix that.

**Comment by chosen1ft** [comment] 2020-10-02 16:07
Good evening!

![1](https://user-images.githubusercontent.com/69076802/94942613-22b40600-0509-11eb-82a8-c28864b86f64.png)
This Hotkey work fine in PMC.But if I complie it to a exe.It doesn't work.Then I open the script file in AutoGUI.The Hotkey become a comment.
![2](https://user-images.githubusercontent.com/69076802/94942852-6ad32880-0509-11eb-844c-894a3454ee9b.png)

Suggestion:
This command work fine in complied exe file(Set hotkey in Expression command and leave the Hotkey Capture Box empty).but can't run in PMC.Is there a way to solve this?(Hotkey decorated with "~")
![3](https://user-images.githubusercontent.com/69076802/94943890-fef1bf80-050a-11eb-96a7-9b1df23451f5.png)

**Comment by Pulover** [comment] 2020-10-02 16:24
For the semicolon hotkey, you have to escape it with a backtick in the script. I don't feel like this should be treated in PMC.

As for your suggestion, I don't understand what you are trying to do or why. As far as I can tell that's not a valid expression.

**Comment by chosen1ft** [comment] 2020-10-02 16:58
About the suggestion: It's a alternative way to set hotkey to Script file.This method can set some hotkeys that PMC doesn't support by now(even Hotstring). Such as "~RButton::" , "MButton & RButton::" , "::btw::"  etc . Enter these into  Expression command.and leave the hotkey capture box empty.then the script file become this:
![6](https://user-images.githubusercontent.com/69076802/94948096-5430cf80-0511-11eb-9f9f-b9aaf8c4fa04.png)

And the hotkey works fine in exe file.

**Comment by Pulover** [comment] 2020-10-02 18:09
It only works because AHK interprets it as a hotkey and compiles it on startup. In PMC it's like writing `(RButton::)` to the script, which is an invalid expression and would throw an error. The expressions window will only evaluate expressions.

But there's a solution for that too. In fact it only needs a few tweaks to make those hotkeys work by inserting them in the edit macro window. I just hadn't tried them before.

**Comment by Pulover** [comment] 2020-10-05 16:07
Problems fixed in v5.2.7.

**Closed** 2020-10-05 16:08 UTC

**Comment by TirOFlanc** [comment] 2021-01-21 16:48
It's exactly that I seach and I need !

Awesome tweak, thanks a lot !
