### ISSUE TITLE
Check for updates fails when use is behind a proxy

### ISSUE THREAD

**Issue by anothermindbomb** [Pulover/PuloversMacroCreator#9] opened 2015-06-12 09:57 UTC
32bit, Windows XP. 

Version 4.1.3 (x86)

By default, "check for updates on startup" is enabled. This fails when you're behind a proxy server, as I am at work. Upon start-up, there is a long pause as the http request times out before you're presented with:

![image](https://cloud.githubusercontent.com/assets/1065272/8127699/d538eef2-10f0-11e5-8775-6f43d3ae2aa8.png)

Hitting "No" shuts the entire application down.

Hitting "Yes" results in 

![image](https://cloud.githubusercontent.com/assets/1065272/8127740/08485238-10f1-11e5-9a4a-08b94badd12d.png)

Again, hitting No shuts down the application

Hitting Yes again allows me to continue to the main screen and start working, where I can turn off "Check for updates on startup"

I can't find anywhere to configure the proxy settings in "Settings" but the application also does not appear to use the IE settings for Proxy configuration either. As far as I can tell, this means I can't check for updates when behind a proxy.

**Comment by Pulover** [comment] 2016-01-04 11:30
Hello,

I have tested the program with proxy here and could not reproduce the error, I suppose you have some more restrictive type of proxy in use. I have added a try statement to this part of the code to avoid the error message. This fix will be in the next release.

**Closed by Pulover** 2016-01-04 11:30 UTC
