### ISSUE TITLE
Edit Macro Bugs.

### ISSUE THREAD

**Issue by chosen1ft** [Pulover/PuloversMacroCreator#105] opened 2020-09-16 11:20 UTC
Thank you for the update!!!

here are some issues I found:

1:Creat new project,then add a new macro tab,then close the first macro,it close all two macro tabs.

2:Creat new project,then add a command ,mouse click,text,or any action.then click "edit macros"button,then just click OK.the action will be deleted automatically. the same bug also happen when you reroder macro tabs by dragging tab in main window.

**Comment by Pulover** [comment] 2020-09-16 16:54
1: I could confirm and have fixed it here.

2: I followed the steps but could not reproduce it here.

**Comment by chosen1ft** [comment] 2020-09-17 11:04
Thank you.

I reinstall PMC .and 2 is OK.My bad.

**Comment by Pulover** [comment] 2020-09-22 12:45
Fixed in v5.2.0.

**Closed by Pulover** 2020-09-22 12:45 UTC
