### ISSUE TITLE
Macrocreator cannot read the name of Macors from a .pmc file.

### ISSUE THREAD

**Issue by LautermF** [Pulover/PuloversMacroCreator#115] opened 2020-10-01 16:16 UTC
Sometimes Macrocreator cannot read the name of Macors from a .pmc file.
If a new macro is created, e.g. Macor23 and renamed to MyMacro and the .pmc file saved, MyMacro can be seen in the .pmc file (in a text editor). If the .pmc file is then opened again, MyMacro suddenly has the name Macro23 again.
I noticed this effect in version 5.0.5 and also in version 5.2.6.

**Comment by LautermF** [comment] 2020-10-01 16:29
I've worked with PMC 5.0.5 so far and this application is just awesome! I am very happy that PMC is going on again!
All my respect for this excellent work!!!

**Comment by Pulover** [comment] 2020-10-01 16:43
Thank you!

Well, I haven't seen this happen. There was an intermittent bug when saving in v5.0.5 but the new one uses a different method to save macro names... This is a difficult one to catch. If you can find a consistent way to reproduce it I can attack it, otherwise there isn't much I can do, I guess...

**Comment by LautermF** [comment] 2020-10-01 16:49
Hi,
I don't think there is a problem with saving, because the correct macro name is in the .pmc file after saving. I checked this with the help of a text editor. The problem only occurs when the file is opened again.

**Comment by chosen1ft** [comment] 2020-10-01 17:19
Maybe you have duplicate macro names.PMC will check macro names as start

**Comment by LautermF** [comment] 2020-10-01 17:29
I've already checked that. There are no double macro names.

**Comment by Pulover** [comment] 2020-10-01 18:39
When that happens, notice if the wrong named tab is also wrong in menu list that shows when you click the ▼ button on the right side of the tabs bar.

**Comment by LautermF** [comment] 2020-10-01 18:48
When I open the .pmc file, I don't make any entries or clicks.
The wrongly named tab can also be seen in the menu list.

**Comment by LautermF** [comment] 2020-10-01 18:58
If when loading the .pmc file all tabs are first created with a default name and then renamed, could the problem occur when renaming?
It looks like the affected tab will not be renamed and will instead keep the default name.
As additional information, the content of the tab that has not been renamed is correct.

**Comment by Pulover** [comment] 2020-10-01 19:14
Probably. You can send me your pmc file and I can make some tests. It can be via email.

**Comment by LautermF** [comment] 2020-10-01 19:24
That is very nice!
I can't send the file until tomorrow because I'm currently not at my computer.
To which e-mail address can I send the file?

**Comment by Pulover** [comment] 2020-10-01 19:29
The one in here https://www.macrocreator.com/contact/

**Comment by Pulover** [comment] 2020-10-01 21:28
I have to correct myself about the maximum number of macros. The tab2 control only seems to support up to 250 tabs or so.
I have to say, however, that this bug must be REALLY rare because I opened 200+ macros at once many times to test it and haven't seen it happen, not even once. Besides, after checking the code I don't see how this could be fixed (if there is a bug at all) since the command to rename the tabs is a native `GuiControl ` command, i.e the official AHK method..

**Comment by LautermF** [comment] 2020-10-02 07:02
Hello,
I looked again at my .pmc file with a text editor and saw something interesting.
The macro names are correctly saved in the .pmc file.
Almost all comments in the .pmc file have the following format:
e.g. 02 | [CommentBlock] | ============================================ ========= | 0 | 1 | CommentBlock ||||||

Some comments in the .pmc file have a number at the end of the line:
e.g. 02 | [CommentBlock] | ============================================ ========= | 0 | 1 | CommentBlock ||||| **2** |

The above Example was also noticed in other places e.g.
14 | LoggingText | _null: = "TRACE", "End macro <FlushPistolOff>" | 1 | 0 | Function ||||||
or
14 | LoggingText | _null: = "TRACE", "End macro <FlushPistolOn>" | 1 | 0 | Function ||||| **33** |

Since these numbers are not present at the end of the line in most cases, my question would be, are these numbers required by PMC?

**Comment by LautermF** [comment] 2020-10-02 07:06
It gives me the impression that these are line numbers.

**Comment by LautermF** [comment] 2020-10-02 09:15
since I like to experiment, I removed these numbers from the .pmc file. PMC was able to load the file. The affected macro then had the wrong name again.

**Comment by LautermF** [comment] 2020-10-02 09:17
After I saved the .pmc file again, the numbers were there again.

**Comment by Pulover** [comment] 2020-10-02 10:01
Yes, those are the numbers of the line of code in the preview panel. You can see the code line column if you scroll to the right. They are used for the go to line/auto-select feature. But this has nothing to do with your problem. The data for the macros are stored in an object, whereas the tab name is read from the header and stored in a variable that's used with `GuiControl` after the data is loaded.

**Comment by LautermF** [comment] 2020-10-02 10:15
I sent the .pmc problem file.

**Comment by LautermF** [comment] 2020-10-02 10:27
For info.
In the past (5.0.5) I had the problem with this file that PMC crashed when loading or saving.
It has also happened that only parts of a macro were saved when saving.

**Comment by Pulover** [comment] 2020-10-02 11:37
I got it. You had, for instance, a macro named _CheckFlushPistolOn_ and then one named _FlushPistolOn_ after that, so the function that checks for duplicate names was matching the first and renaming the second. Changing the check from `InStr() ` to `RegExMatch()` fixed the problem.

**Comment by LautermF** [comment] 2020-10-02 11:39
Great!
You are perfect!

**Comment by LautermF** [comment] 2020-10-02 11:41
> 
> 
> For info.
> In the past (5.0.5) I had the problem with this file that PMC crashed when loading or saving.
> It has also happened that only parts of a macro were saved when saving.

have other users observed these problems in the past?

**Comment by Pulover** [comment] 2020-10-02 11:50
Yes, it was a known issue for v5 before I got back to this project two months ago. #11, #34, #50, #51, #53, #60, #74, #94

**Comment by LautermF** [comment] 2020-10-02 12:32
OK.
Now I am looking forward to the new version >5.2.6 of PMC!
Thank you very much for your help and stay healthy!

**Comment by Pulover** [comment] 2020-10-05 16:08
Fixed in v5.2.7.

**Closed by Pulover** 2020-10-05 16:08 UTC
